# Content configuration version
version: 2

# Personal info
name: Jonas Werheid
title: Consultant & Scientific Researcher | Manufacturing & Data Science
email: jonas.werheid@rwth-aachen.de
contact: https://www.linkedin.com/in/jonas-w-12ab05195/

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  jonaswer
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: https://www.linkedin.com/in/jonas-w-12ab05195/
# xing_username: jekyll
# pinterest_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000
# researchgate_username: https://www.researchgate.net/profile/Jonas-Werheid-2

# Additional icon links
# additional_links:
# - title: ResearchGate
#  icon: images/RG.png
#  url: https://www.researchgate.net/profile/Jonas-Werheid-2
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Hi, I'm Jonas!

 As a Consultant and Scientific Researcher, I specialize in optimizing data management and developing machine learning applications for the manufacturing industry. 
 My expertise spans industrial consultancy, service development, and leadership in publicly funded projects that produce open-access research outputs. 
 For more insight into my research background, my publications can be found on [ResearchGate](https://www.researchgate.net/profile/Jonas-Werheid-2).

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: ZUKIPRO
        link: https://zukipro.de/
        # link_text: Project Website
        #additional_links:
        #  - title:  Webpage
            #icon: fab fa-github
        #    url: https://nfdi4ing.de/
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #quote: >
        #  This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          ZUKIPRO Future Center is specifically aimed at transforming small and medium-sized enterprises in Hessen, Germany. Seven strong partners are pursuing the goal of bringing digitalization and human-centered AI specifically into use in Hessian production and craft businesses. Our free services include the pillars of informing, consulting, and training, and are aimed at both employers and employees.
      
      - layout: top-middle
        title: NFDI4ing
        link: https://nfdi4ing.de/
        # link_text: Project Website
        #additional_links:
        #  - title:  Webpage
            #icon: fab fa-github
        #    url: https://nfdi4ing.de/
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #quote: >
        #  This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          NFDI4Ing represents the German engineering research landscape. The consortium brings together institutions and individuals from all areas of the engineering landscape, each contributing their specific expertise, experience, and contacts to the consortium’s work program. NFDI4Ing thus enables the close collaboration of engineering scientists, service providers, and users to work towards the common goal of realizing the FAIR principles of scientific data management in the engineering sciences.
  - title: Experience
    layout: list
    content:
    - layout: left
      title: Laboratory for Machine Tools and Production Engineering (WZL), RWTH Aachen University
      sub_title: Consultant and Scientific Researcher
      caption: March 2023 - Present
      quote: >
        Management and participation in industrial and publicly funded projects, acquisition activities, university teaching, and supervision of theses.
      description: | 
        My work focus on sustainable data management and computer vision for manufacturing industries. My role includes management of industrial projects, research, and academic responsibilities such as thesis supervision and publishing scientific articles. I also engage in acquisition activities for research funding.

    - layout: left
      title: Laboratory for Machine Tools and Production Engineering (WZL), RWTH Aachen University
      sub_title: Graduate Research Assistant
      caption: October 2021 - February 2023
      quote: >
        Development of software architectures for full-stack web applications and machine vision in manufacturing environments.
      description: | 
        In this role, I worked on software solutions for cross-institute research projects. I contributed to the development of DevOps applications and implemented machine vision techniques for use in manufacturing settings, focusing on improving efficiency and automation.

    - layout: left
      title: Institute for Machine Elements and Systems Engineering, RWTH Aachen University
      sub_title: Graduate Research Assistant
      caption: January 2021 - March 2022
      quote: >
        Development of simulation models for advanced plastic-metal bonding techniques in automotive assembly.
      description: | 
        I contributed to research on laser-based plastic-metal bonding techniques used in automotive manufacturing. My primary task was developing simulation models that support process optimization and enhanced material bonding quality for laser-based plastic metal joinings.

    - layout: left
      title: Robert Bosch GmbH
      sub_title: Intern
      caption: September 2020 - January 2021
      quote: >
        Implementing computer vision solutions to improve quality control in electronics manufacturing.
      description: | 
        During this internship, I worked on computer vision techniques for the automated inspection of printed circuit boards in the electronics manufacturing process. This improved the quality and reliability of electronic components through advanced image processing methods.

    - layout: left
      title: Laboratory for Machine Tools and Production Engineering (WZL), RWTH Aachen University
      sub_title: Student Assistant
      caption: March 2020 - September 2020
      quote: >
        Assisting with experiments and software development for advanced grinding technologies.
      description: | 
        I supported various research activities related to grinding technology. My contributions included assisting with experiments, performing laboratory measurements, and developing software solutions for data analysis and process optimization.

    - layout: left
      title: Eisenwerk Brühl GmbH
      sub_title: Intern
      caption: June 2017 - July 2017
      quote: >
        Supporting production processes in the iron casting of automotive engine components.
      description: | 
        As an intern, I contributed to the iron casting production process used for automotive engines. I assisted with the coordination of production workflows and performed process optimizations to enhance the overall quality of the cast parts.


  - title: Education
    layout: list
    content:
    - layout: left
      title: RWTH Aachen University
      caption: 2023 - 2027 (expected)
      sub_title: Doctor of Philosophy (PhD), Dr.-Ing (PhD) - Mechanical Engineering
      quote: >
        RWTH Aachen University is one of Europe’s leading technical universities, renowned for its strong focus on engineering and research in industrial technologies.
      description: | 
        Pursuing a PhD with a focus on computer vision techniques for manufacturing processes. My research aims to develop innovative solutions for industrial challenges through the integration of advanced GenAI technologies.

    - layout: left
      title: RWTH Aachen University
      caption: 2020 - 2022
      sub_title: Master of Science (MS), Industrial Engineering - Production Technology & Operations Research
      quote: >
        A program that bridges industrial engineering with advanced operations research techniques to optimize production processes.
      description: | 
        My Master's studies were focused on enhancing production technologies and improving operational efficiency with mathematical optimization and machine learning algorithms. 

    - layout: left
      title: Universidad de Navarra
      caption: 2019 - 2020
      sub_title: Económicas y Empresariales / Economics and Business Administration
      quote: >
        Universidad de Navarra is an internationally recognized institution, known for its interdisciplinary approach and fostering global perspectives in economics and business.
      description: | 
        During my exchange program at Universidad de Navarra, I studied various aspects of economics and business administration, which provided a broader understanding of management and business operations in global contexts.

    - layout: left
      title: RWTH Aachen University
      caption: 2017 - 2020
      sub_title: Bachelor of Science (BS), Industrial Engineering - Mechanical Engineering & Management
      quote: >
        RWTH Aachen is known for combining engineering expertise with management skills, creating well-rounded graduates ready to tackle modern industrial challenges.
      description: | 
        My Bachelor's degree focused on the intersection of mechanical engineering and management, where I developed foundational knowledge in production systems, mechanical engineering principles, and business management. This laid the groundwork for my professional endeavors.


  - title: Certifications
    layout: list
    content:
      - layout: left
        title: Leadership Competence Review
        sub_title: RWTH Doctoral Academy
        caption: Issued on August 2024
        description: This workshop focuses on personal reflection on leadership behavior, using feedback as a key leadership tool through case studies from real-world leadership scenarios. Participants will learn how to develop and refine their leadership profile, implement decisions with confidence, engage and influence others effectively, assert themselves while maintaining strong relationships, and enrich their leadership approach with constructive feedback. Additionally, the workshop will help participants recognize strengths and weaknesses in delegating and monitoring tasks, enhancing their overall leadership capabilities.
      - layout: left
        title: Working in International Teams
        sub_title: RWTH Doctoral Academy
        caption: Issued on April 2024
        description: This course provides an introduction to the German higher education landscape, focusing on the challenges faced by both international and German researchers. Participants will learn to assess cultural factors in a professional context and adapt their behavior accordingly. The course also emphasizes the importance of active relationship management with various stakeholders in the academic sector. Additionally, it fosters an understanding of diverse team backgrounds and highlights the benefits that arise from this diversity in a collaborative environment.

  - title: Other Experiences
    layout: list
    content:
    - layout: left
      title: A few Personal Programming Projects
      description: |
        1. [synographs.herokuapp.com](https://synographs.herokuapp.com): Webpage for searching synonym chains (graph-based combinatorial optimization).
        2. [computational-ego.herokuapp.com](https://computational-ego.herokuapp.com): Webpage for a psychological free-field test (Deep Learning).

        Both projects are implemented in Flask (backend) and Javascript (frontend), and deployed with a GitLab CI/CD Pipeline as Heroku cloud applications.
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag