# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jonas Werheid
title: Consultant & Scientific Researcher
email: [jonas.werheid@rwth-aachen.de]
website: [Your Website]

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: [Your GitHub Username]
linkedin_username: [Your LinkedIn Username]
researchgate_username: [Your ResearchGate Username]

# About Section
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Jonas!

  As a Consultant and Scientific Researcher, I specialize in optimizing data management and developing machine learning applications for the manufacturing industry. My expertise spans industrial consultancy, service development, and leadership in publicly funded projects that produce open-access research outputs.

  Highly team-oriented and committed to delivering real-world value, I prioritize effective communication with team members and stakeholders to ensure that project goals are met efficiently.

  **I am most skilled in:**  
  - Sustainable Data Management  
  - Machine Learning for Manufacturing  
  - Software Development (Data Analytics, Data Visualization, MLOps/DevOps, Web Applications, Data Warehousing)

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: ZUKIPRO
        link: [Project Link]
        additional_links:
          - title: ResearchGate Profile
            icon: fas fa-globe
            url: [Your ResearchGate URL]
        description: | # this will include new lines to allow paragraphs
          Participation in publicly funded projects focusing on sustainable data management and computer vision techniques for the manufacturing industry.

      - layout: top-middle
        title: NFDI4Ing
        link: [Project Link]
        additional_links:
          - title: ResearchGate Profile
            icon: fas fa-globe
            url: [Your ResearchGate URL]
        description: | # this will include new lines to allow paragraphs
          Leadership in service development and involvement in acquisition activities, contributing to open-access research outputs.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Laboratory for Machine Tools and Production Engineering (WZL) of RWTH Aachen University
        link: [Company Website]
        sub_title: Consultant and Scientific Researcher
        caption: March 2023 - Present
        description: | # this will include new lines to allow paragraphs
          - Management and participation in industrial and publicly funded projects.
          - Involvement in acquisition activities, university teaching, and thesis supervision.
          - Focus on sustainable data management and computer vision techniques for the manufacturing industry.

      - layout: left
        title: Laboratory for Machine Tools and Production Engineering at RWTH Aachen University (WZL)
        link: [Company Website]
        sub_title: Graduate Research Assistant
        caption: October 2021 - February 2023
        description: | # this will include new lines to allow paragraphs
          - Development of software architectures for full-stack web applications in cross-institute research projects.
          - DevOps applications for machine vision in manufacturing environments.

      - layout: left
        title: Institute for Machine Elements and Systems Engineering at RWTH Aachen University
        link: [Company Website]
        sub_title: Graduate Research Assistant
        caption: January 2021 - March 2022
        description: | # this will include new lines to allow paragraphs
          - Development of simulation models for laser-based plastic-metal bonding in automotive assembly processes.

      - layout: left
        title: Robert Bosch GmbH
        link: [Company Website]
        sub_title: Intern
        caption: September 2020 - January 2021
        description: | # this will include new lines to allow paragraphs
          - Development of computer vision techniques for automated quality inspection of printed circuit boards in electronics manufacturing.

      - layout: left
        title: Laboratory for Machine Tools and Production Engineering at RWTH Aachen University (WZL)
        link: [Company Website]
        sub_title: Student Assistant
        caption: March 2020 - September 2020
        description: | # this will include new lines to allow paragraphs
          - Assistance in performing experiments and conducting laboratory measurements.
          - Development of software related to grinding technology.

      - layout: left
        title: Eisenwerk Brühl GmbH
        link: [Company Website]
        sub_title: Intern
        caption: June 2017 - July 2017
        description: | # this will include new lines to allow paragraphs
          - Assistance in production processes for iron casting in automotive engine manufacturing.

  - title: Education
    layout: list
    content:
      - layout: left
        title: RWTH Aachen University
        caption: 2023 - 2027 (Expected)
        sub_title: Doctor of Philosophy (PhD), Mechanical Engineering
        description: | # this will include new lines to allow paragraphs
          Pursuing a PhD with a focus on sustainable data management and machine learning methods for the manufacturing industry.

      - layout: left
        title: RWTH Aachen University
        caption: 2020 - 2022
        sub_title: Master of Science (MS), Industrial Engineering - Production Technology & Operations Research
        description: | # this will include new lines to allow paragraphs
          Specialized in production technology and operations research, developing skills in optimization and industrial processes.

      - layout: left
        title: Universidad de Navarra
        caption: 2019 - 2020
        sub_title: Economics and Business Administration
        description: | # this will include new lines to allow paragraphs
          Studied economics and business administration, gaining insights into financial systems and business strategies.

  - title: Certifications
    layout: list
    content:
      - layout: left
        title: Leadership Competence Review
        sub_title: RWTH Doctoral Academy
        caption: Issued August 2024

      - layout: left
        title: Working in International Teams
        sub_title: RWTH Doctoral Academy
        caption: Issued April 2024

  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      **Engineering Tools:**  
      - SolidWorks  
      - Siemens NX  
      - Cameo Systems Modeler  
      - AutoCAD  

      **Data Science:**  
      - TensorFlow  
      - Keras  
      - Scikit-learn  
      - Gurobi  
      - HuggingFace  

      **Web Development:**  
      - Django  
      - Flask  
      - PHP  
      - SQL  
      - JavaScript  
      - Angular  
      - HTML/CSS  

      **DevOps:**  
      - AWS  
      - Salesforce Cloud  
      - GitHub Actions  
      - GitLab CI/CD

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      **Languages:**  
      - English: Native or Bilingual  
      - German: Native or Bilingual  
      - Spanish: Fluent  

      **Interests and Hobbies:**  
      - Research in Engineering  
      - Software Development Projects  
      - Machine Learning Applications  
      - Open-Access Publications

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
